### Python libraries for datascience

#### Numpy
* Numerical Python or Numeric python
* Numpy is programming language that deals with multi dimensional arrays and Matrices
* it supports a large number of mathematical operations
### why we use numpy
* Numpy is memory efficiency
* maatrix multiplication and reshaping
* on top of that,Numpy is fast.

### How to install Numpy
* Numpy is installed by default in anconda

In [1]:
import numpy as np

In [2]:
print(np.__version__)

1.16.2


### Numpy arrays

In [4]:
#1D Array
print(np.array([1,2,3,4]))

[1 2 3 4]


In [6]:
#2D array
data=np.array([[1,3,5,7],[2,4,6,8]])
data

array([[1, 3, 5, 7],
       [2, 4, 6, 8]])

In [10]:
#Mathematical operations
a1=np.array([2,6,8,9])
a2=np.array([3,4,7,5])
a1+a2

array([ 5, 10, 15, 14])

In [12]:
#shape of array
data=np.array([[1,2,3,4],[5,6,7,8]])
data1=np.array([[1.1,2.2,3.3,4.4,5.5],[6.6,7.7,8.8,9.9,1.0]])
print(np.shape(data))

(2, 4)


In [13]:
print(np.shape(data1))

(2, 5)


In [20]:
print(data.dtype)

int32


In [25]:
print(data1.dtype)

float64


In [29]:
d=np.array([1,'2',3])
print(d.dtype)

<U11


In [ ]:
#numpy zeros and ones

In [14]:
#numpy zeros
#syntax:zeros(dimension,datatype)
np.zeros((3,2),dtype=int)

array([[0, 0],
       [0, 0],
       [0, 0]])

In [15]:
np.zeros((2,4),dtype=float)

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [19]:
np.zeros((3,3),dtype='str')

array([['', '', ''],
       ['', '', ''],
       ['', '', '']], dtype='<U1')

In [30]:
#syntx:ones(dimension,datatype)
np.ones((3,2),dtype=float)

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [31]:
np.ones((3,2),dtype="str")

array([['1', '1'],
       ['1', '1'],
       ['1', '1']], dtype='<U1')

In [42]:
#numpy reshape
data2=np.array([[1,2,3,4,5],[5,6,7,8,9],[2,6,8,4,9]])
print(data2)

[[1 2 3 4 5]
 [5 6 7 8 9]
 [2 6 8 4 9]]


In [43]:
print(data2.reshape(5,3))

[[1 2 3]
 [4 5 5]
 [6 7 8]
 [9 2 6]
 [8 4 9]]


In [44]:
#numpy flatten
data2.flatten()

array([1, 2, 3, 4, 5, 5, 6, 7, 8, 9, 2, 6, 8, 4, 9])

In [45]:
print(a1)
print(a2)

[2 6 8 9]
[3 4 7 5]


In [57]:
#numpy hstack(data apended horizontally)
d3=np.hstack((a1,a2))

In [58]:
d3

array([2, 6, 8, 9, 3, 4, 7, 5])

In [59]:
#numpy vstack(data appended vertically)
d4=np.vstack((d3))
d4

array([[2],
       [6],
       [8],
       [9],
       [3],
       [4],
       [7],
       [5]])

In [61]:
#Numpy Statistical functions(min,max,mean,standard deviation)
d=np.array([[25,31,1,6],[7,8,9,10]])
d

array([[25, 31,  1,  6],
       [ 7,  8,  9, 10]])

In [62]:
d.min()

1

In [63]:
d.max()

31

In [64]:
d.mean()

12.125

In [65]:
d.std()

9.623376486452143

In [66]:
d

array([[25, 31,  1,  6],
       [ 7,  8,  9, 10]])

In [67]:
d.T

array([[25,  7],
       [31,  8],
       [ 1,  9],
       [ 6, 10]])

In [68]:
d.transpose()

array([[25,  7],
       [31,  8],
       [ 1,  9],
       [ 6, 10]])

In [69]:
a1

array([2, 6, 8, 9])

In [70]:
print(np.sin(a1))

[ 0.90929743 -0.2794155   0.98935825  0.41211849]


In [72]:
#generate random numbers
d1=np.random.randint(1,50,(3,5))
d1

array([[44, 45, 38, 35, 15],
       [20, 13, 36, 45, 42],
       [40, 43, 22, 37, 24]])

In [73]:
#syntax:normal(loc(mean),scale(std),size(no of elements))
d2=np.random.normal(5,4,10)

In [74]:
d2

array([6.86047685, 5.62890479, 7.80924704, 2.8107399 , 1.6454001 ,
       4.11909188, 3.43566816, 7.53531735, 5.08505165, 4.97622201])

In [75]:
#power
a=np.array([1,2,3,4,5])
np.array([a,pow(a,3)])

array([[  1,   2,   3,   4,   5],
       [  1,   8,  27,  64, 125]])

In [76]:
#identity matrix
np.eye(4,dtype=int)

array([[1, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 1, 0],
       [0, 0, 0, 1]])

In [77]:
a=np.array([2,4,6,8])
b=np.array([5,7,9,3])
c=a.dot(b)
c

116

In [78]:
#arange function
#syntax:arange(start,stop,step)
np.arange(1,11)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [79]:
np.arange(1,11,2)

array([1, 3, 5, 7, 9])

In [80]:
np.arange(1,20,3)

array([ 1,  4,  7, 10, 13, 16, 19])

In [82]:
#numpy linspace(default=50)
#syntax:linspace(start,stop,num of elements)
np.linspace(1,6,num=10)

array([1.        , 1.55555556, 2.11111111, 2.66666667, 3.22222222,
       3.77777778, 4.33333333, 4.88888889, 5.44444444, 6.        ])

In [83]:
np.linspace(1,5)

array([1.        , 1.08163265, 1.16326531, 1.24489796, 1.32653061,
       1.40816327, 1.48979592, 1.57142857, 1.65306122, 1.73469388,
       1.81632653, 1.89795918, 1.97959184, 2.06122449, 2.14285714,
       2.2244898 , 2.30612245, 2.3877551 , 2.46938776, 2.55102041,
       2.63265306, 2.71428571, 2.79591837, 2.87755102, 2.95918367,
       3.04081633, 3.12244898, 3.20408163, 3.28571429, 3.36734694,
       3.44897959, 3.53061224, 3.6122449 , 3.69387755, 3.7755102 ,
       3.85714286, 3.93877551, 4.02040816, 4.10204082, 4.18367347,
       4.26530612, 4.34693878, 4.42857143, 4.51020408, 4.59183673,
       4.67346939, 4.75510204, 4.83673469, 4.91836735, 5.        ])

In [84]:
#indexing slicing
import numpy as np
x=np.array([[1,2,3],[4,5,6]])
x

array([[1, 2, 3],
       [4, 5, 6]])

In [85]:
x[:]

array([[1, 2, 3],
       [4, 5, 6]])

In [86]:
x[::-1]

array([[4, 5, 6],
       [1, 2, 3]])

In [87]:
x[0]

array([1, 2, 3])

In [88]:
x[1]

array([4, 5, 6])

In [89]:
print(x)
x[:,1]

[[1 2 3]
 [4 5 6]]


array([2, 5])